white: 
  Pawn: a2 b2 c2 d2 e2 f2 g2 h2
  Knight: b1 g1
  Bishop: c1 f1
  Tower: a1 h1
  Queen: d1
  King: e1

black:
  Pawn: a7 b7 c7 d7 e7 f7 g7 h7
  Knight: b8 g8
  Bishop: c8 f8
  Tower: a8 h8
  Queen: d8
  King: e8